import { z } from 'zod';

/**
 * Supported transaction type enum values
 */
export const transactionTypeSchema = z.enum(['income', 'expense', 'transfer']);
export type TransactionType = z.infer<typeof transactionTypeSchema>;

/**
 * Normalized Transaction Schema
 * Serves as the universal contract between main application data and AI service features.
 */
export const transactionSchema = z.object({
  id: z.string().min(1, 'Transaction ID is required'),
  userId: z.string().min(1, 'User ID is required'),
  amount: z.number({ required_error: 'Amount is required' }).finite('Amount must be a valid finite number'),
  type: transactionTypeSchema,
  date: z.string().min(1, 'Date string is required'),
  merchant: z.string().optional(),
  description: z.string().optional(),
  category: z.string().optional(),
  accountId: z.string().optional(),
  currency: z.string().min(1, 'Currency code is required'),
});

export type NormalizedTransaction = z.infer<typeof transactionSchema>;

/**
 * Supported categorization prediction method enum values
 */
export const categoryPredictionMethodSchema = z.enum(['rule', 'llm', 'fallback']);
export type CategoryPredictionMethod = z.infer<typeof categoryPredictionMethodSchema>;

/**
 * Category Prediction Result Schema
 * Contract for output generated by categorization engines.
 */
export const categoryPredictionSchema = z.object({
  category: z.string().min(1, 'Predicted category is required'),
  confidence: z.number().min(0).max(1),
  method: categoryPredictionMethodSchema,
});

export type CategoryPrediction = z.infer<typeof categoryPredictionSchema>;
